name: Run tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '19.x'
        cache: 'npm'
        cache-dependency-path: src/package-lock.json
    - name: Install packages
      run: |
        cd ./src 
        npm ci
    - name: Linting and Static Code Analysis
      run: |
        npm run test-lint --prefix src
    - name: Integration Tests
      env:
        MONGO_URL: mongodb://localhost:27017/notes-app-test
      run: |
        docker-compose up -d
        npm run test-integration --prefix src
        docker-compose down
    - name: Unit coverage
      run: |
        cd ./src
        npm run test-unit --prefix src
    - name: npm run test:e2e
      run: |
        cd ./src
        npm run test-e2e --prefix src